services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: brightodedame
      POSTGRES_PASSWORD: Oluchi1996
      POSTGRES_DB: userdatabase
      PGDATA: /data/postgres
    volumes:
      - postgres4:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - backend
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin_container_4
    image: dpage/pgadmin4
    mem_limit: 700m
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - pgadmin4:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - backend
    restart: unless-stopped
  mongo:
    image: mongo:latest
    container_name: mongo_container_4
    ports:
      - 27017:27017
    volumes:
      - mongodata:/data/db
    networks:
      - backend
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq_4
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - backend
    volumes:
      - rabbitmqdataa:/var/lib/rabbitmq
    hostname: rabbitmq
    restart: unless-stopped
 
  seq:
    image: datalust/seq
    container_name: seq
    environment: 
      - ACCEPT_EULA=Y
    ports:
      - 5341:5341
      - 80:80
    networks:
      - backend
    volumes:
      - seqdata:/data

  jaeger:
    image: jaegertracing/all-in-one
    container_name: jaeger
    ports:
      - 5778:5778
      - 6831:6831/udp
      - 6832:6832/udp
      - 14250:14250
      - 14268:14268
      - 16686:16686

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus/otel.yml:/etc/prometheus/prometheus.yml
      - prometheusdata:/prometheus


networks:
  backend:
    driver: bridge
volumes:
  mongodata:
  rabbitmqdataa:
  postgres4:
  pgadmin4:
  seqdata:
  prometheusdata:
